server:
  port: 1002
#spring cloud eureka优先使用spring.application.name值来覆盖eureka.instance.appname的值
spring:
  application:
    name: server-great-snow

info:
  app:
    name: @project.artifactId@
  build:
    artifactId: @project.artifactId@
    version: @project.version@
  author:
    name: great-snow

eureka:
  dashboard:
    path: / #default:'/', eureka web ui访问路径
  instance:
    hostname: @project.artifactId@
    appname: server #服务名，默认取 spring.application.name 配置值，如果没有则为 unknown
    #prefer-ip-address,default:'false':不使用主机名,而使用IP地址来定义注册中心的地址，如果设置了ip-address属性，则使用该属性配置的IP，否则自动获取除环路IP外的第一个IP地址
    prefer-ip-address: false
    instance-id: ${eureka.instance.hostname}:${server.port}
    lease-renewal-interval-in-seconds: 30 #定义服务续约任务（心跳）的调用间隔，单位：秒
    lease-expiration-duration-in-seconds: 90 #定义服务失效的时间，单位：秒
  client:
    healthcheck:
      enabled: true
    fetch-registry: false #default:'true' 此客户端是否获取eureka服务器注册表上的注册信息
    register-with-eureka: false #default:'true' 实例是否在eureka服务器上注册自己的信息以供其他服务发现
    registery-fetch-interval-seconds: 30 #default:'30'从Eureka服务器端获取注册信息的间隔时间，单位：秒
    eureka-server-connect-timeout-seconds: 5 #default:'5'连接 Eureka Server 的超时时间，单位：秒
    eureka-server-read-timeout-seconds: 8 #default:'8'读取 Eureka Server 信息的超时时间，单位：秒
    eureka-connection-idle-timeout-seconds: 30 #default:'30' Eureka 服务端连接空闲关闭时间，单位：秒
    eureka-server-total-connections: 200 #default:'200' 从Eureka 客户端到所有Eureka服务端的连接总数
    eureka-server-total-connections-per-host: 50 #default:'50' 从Eureka客户端到每个Eureka服务主机的连接总数
    filter-only-up-instances: true #default:'true' 获取实例时是否过滤，只保留UP状态的实例
    prefer-same-zone-eureka: true
    region: DaLian
    availability-zones:
     DaLian: LightSnow,GreatSnow,AllZone
    service-url:
      LightSnow: http://eureka-server:eureka-server@server-light-snow:1001/eureka/
      GreatSnow: http://eureka-server:eureka-server@server-great-snow:1002/eureka/
      AllZone: http://eureka-server:eureka-server@server-light-snow:1001/eureka/,http://eureka-server:eureka-server@server-great-snow:1002/eureka/
  server:
    eviction-interval-timer-in-ms: 10000 #清理间隔10s
    enable-self-preservation: false  #default:'true'自我保护,默认开启状态
  
#如果prefer-same-zone-eureka:false,按照service-url下的list取第一个注册中心来注册，并维持心跳检测，不会再向list内的其他的注册中心注册和维持心跳，
#只有在第一个注册失败的情况，才会依次向其他注册中心注册，总共三次，如果三次service-url都没有注册成功，则注册失败，每隔一个心跳时间会再次尝试。
#如果prefer-same-zone-eureka:true,先通过region取availability-zones内的第一个zone,然后通过这个Zone取service-url下的List，
#并向list内的第一个注册中心注册和维持心跳，不会再向List内的其他注册中心注册，只有在第一个注册失败的情况下才会依次向其他注册中心注册，总共三次，
#如果三次service-url都没有注册成功，则注册失败，每隔一个心跳时间会再次尝试。

#enable-self-preservation:true.关闭自我保护,默认开启状态   
#关闭注册中心的保护机制，Eureka会统计15分钟之内心跳失败的比例低于85%将会触发保护机制，不剔除服务提供者，如果关闭服务注册中心将不可用的实例正确剔除. 

#service-url:指定服务注册中心地址，类型为 HashMap，并设置有一组默认值，默认的Key为 defaultZone；
#默认的Value为 http://localhost:8761/eureka，如果服务注册中心为高可用集群时，多个注册中心地址以逗号分隔。
